services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - PYTHONPATH=/app/backend
    volumes:
      - ./backend/app.db:/app/backend/app.db

  frontend:
    build: ./frontend
    ports:
      - "3005:80"
    depends_on:
      - backend 